package mybatis.model.complex;

import flexjson.JSON;
import mybatis.model.basic.Country;

public class Region {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.region.id
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.region.name
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */

    private String name;
    private String area1;

    private Country country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.region.id_country
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    private Long idCountry;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.region.id
     *
     * @return the value of webserver.region.id
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.region.id
     *
     * @param id the value for webserver.region.id
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.region.name
     *
     * @return the value of webserver.region.name
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.region.name
     *
     * @param name the value for webserver.region.name
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.region.id_country
     *
     * @return the value of webserver.region.id_country
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public Long getIdCountry() {
        return idCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.region.id_country
     *
     * @param idCountry the value for webserver.region.id_country
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public void setIdCountry(Long idCountry) {
        this.idCountry = idCountry;
    }

    @JSON
    public Country getCountry() {
        return country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    public String getArea1() {
        return area1;
    }

    public void setArea1(String area1) {
        this.area1 = area1;
    }
}