package mybatis.model.basic;

public class Country {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.country.id
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.country.name
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.country.iso2_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    private String iso2Code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.country.iso3_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    private String iso3Code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.country.iso_num_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    private Integer isoNumCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.country.dial_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    private Integer dialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.country.iso_full_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    private String isoFullCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.country.id
     *
     * @return the value of webserver.country.id
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.country.id
     *
     * @param id the value for webserver.country.id
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.country.name
     *
     * @return the value of webserver.country.name
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.country.name
     *
     * @param name the value for webserver.country.name
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.country.iso2_code
     *
     * @return the value of webserver.country.iso2_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public String getIso2Code() {
        return iso2Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.country.iso2_code
     *
     * @param iso2Code the value for webserver.country.iso2_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public void setIso2Code(String iso2Code) {
        this.iso2Code = iso2Code == null ? null : iso2Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.country.iso3_code
     *
     * @return the value of webserver.country.iso3_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public String getIso3Code() {
        return iso3Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.country.iso3_code
     *
     * @param iso3Code the value for webserver.country.iso3_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public void setIso3Code(String iso3Code) {
        this.iso3Code = iso3Code == null ? null : iso3Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.country.iso_num_code
     *
     * @return the value of webserver.country.iso_num_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public Integer getIsoNumCode() {
        return isoNumCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.country.iso_num_code
     *
     * @param isoNumCode the value for webserver.country.iso_num_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public void setIsoNumCode(Integer isoNumCode) {
        this.isoNumCode = isoNumCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.country.dial_code
     *
     * @return the value of webserver.country.dial_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public Integer getDialCode() {
        return dialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.country.dial_code
     *
     * @param dialCode the value for webserver.country.dial_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public void setDialCode(Integer dialCode) {
        this.dialCode = dialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.country.iso_full_code
     *
     * @return the value of webserver.country.iso_full_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public String getIsoFullCode() {
        return isoFullCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.country.iso_full_code
     *
     * @param isoFullCode the value for webserver.country.iso_full_code
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public void setIsoFullCode(String isoFullCode) {
        this.isoFullCode = isoFullCode == null ? null : isoFullCode.trim();
    }
}