package mybatis.model.basic;

public class EventFilter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event_filter.id
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event_filter.id_user
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    private Long idUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event_filter.id_event_type
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    private Long idEventType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event_filter.id
     *
     * @return the value of webserver.event_filter.id
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event_filter.id
     *
     * @param id the value for webserver.event_filter.id
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event_filter.id_user
     *
     * @return the value of webserver.event_filter.id_user
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public Long getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event_filter.id_user
     *
     * @param idUser the value for webserver.event_filter.id_user
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event_filter.id_event_type
     *
     * @return the value of webserver.event_filter.id_event_type
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public Long getIdEventType() {
        return idEventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event_filter.id_event_type
     *
     * @param idEventType the value for webserver.event_filter.id_event_type
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public void setIdEventType(Long idEventType) {
        this.idEventType = idEventType;
    }
}