package mybatis.model.basic;

public class EventTypeMN {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event_type_mn.id
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event_type_mn.id_event
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    private Long idEvent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event_type_mn.id_event_type
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    private Long idEventType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event_type_mn.id
     *
     * @return the value of webserver.event_type_mn.id
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event_type_mn.id
     *
     * @param id the value for webserver.event_type_mn.id
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event_type_mn.id_event
     *
     * @return the value of webserver.event_type_mn.id_event
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public Long getIdEvent() {
        return idEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event_type_mn.id_event
     *
     * @param idEvent the value for webserver.event_type_mn.id_event
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public void setIdEvent(Long idEvent) {
        this.idEvent = idEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event_type_mn.id_event_type
     *
     * @return the value of webserver.event_type_mn.id_event_type
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public Long getIdEventType() {
        return idEventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event_type_mn.id_event_type
     *
     * @param idEventType the value for webserver.event_type_mn.id_event_type
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public void setIdEventType(Long idEventType) {
        this.idEventType = idEventType;
    }
}