package mybatis.model.basic;

import java.util.Date;

public class Event {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event.id
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event.name
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event.is_public
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    private Boolean isPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event.time
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    private Date time;


    private Date created;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event.capacity
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    private Integer capacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event.description
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event.id_owner
     *
     * @mbggenerated Sat Jan 03 18:12:45 CET 2015
     */
    private Long idOwner;


    private Long idAddress;



    private Boolean requireConfirm;



    public Boolean getRequireConfirm() {
        return requireConfirm;
    }

    public void setRequireConfirm(Boolean requireConfirm) {
        this.requireConfirm = requireConfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event.id
     *
     * @return the value of webserver.event.id
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public Long getId() {
        return id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event.id
     *
     * @param id the value for webserver.event.id
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event.name
     *
     * @return the value of webserver.event.name
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event.name
     *
     * @param name the value for webserver.event.name
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event.is_public
     *
     * @return the value of webserver.event.is_public
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public Boolean getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event.is_public
     *
     * @param isPublic the value for webserver.event.is_public
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event.time
     *
     * @return the value of webserver.event.time
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event.time
     *
     * @param time the value for webserver.event.time
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event.capacity
     *
     * @return the value of webserver.event.capacity
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event.capacity
     *
     * @param capacity the value for webserver.event.capacity
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event.description
     *
     * @return the value of webserver.event.description
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event.description
     *
     * @param description the value for webserver.event.description
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event.id_owner
     *
     * @return the value of webserver.event.id_owner
     *
     * @mbggenerated Sat Jan 03 18:12:45 CET 2015
     */
    public Long getIdOwner() {
        return idOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event.id_owner
     *
     * @param idOwner the value for webserver.event.id_owner
     *
     * @mbggenerated Sat Jan 03 18:12:45 CET 2015
     */
    public void setIdOwner(Long idOwner) {
        this.idOwner = idOwner;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event.id_address
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public Long getIdAddress() {
        return idAddress;
    }

    public void setIdAddress(Long idAddress) {
        this.idAddress = idAddress;
    }


    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }
}