package mybatis.model.basic;

public class EventType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event_type.id
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.event_type.type_name
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event_type.id
     *
     * @return the value of webserver.event_type.id
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event_type.id
     *
     * @param id the value for webserver.event_type.id
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.event_type.type_name
     *
     * @return the value of webserver.event_type.type_name
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.event_type.type_name
     *
     * @param typeName the value for webserver.event_type.type_name
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}