package mybatis.model.basic;

public class LocalityFilter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.locality_filter.id
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.locality_filter.id_user
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    private Long idUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.locality_filter.id_region
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    private Long idRegion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.locality_filter.id
     *
     * @return the value of webserver.locality_filter.id
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.locality_filter.id
     *
     * @param id the value for webserver.locality_filter.id
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.locality_filter.id_user
     *
     * @return the value of webserver.locality_filter.id_user
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public Long getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.locality_filter.id_user
     *
     * @param idUser the value for webserver.locality_filter.id_user
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.locality_filter.id_region
     *
     * @return the value of webserver.locality_filter.id_region
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public Long getIdRegion() {
        return idRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.locality_filter.id_region
     *
     * @param idRegion the value for webserver.locality_filter.id_region
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    public void setIdRegion(Long idRegion) {
        this.idRegion = idRegion;
    }
}