package mybatis.model.basic;

public class Notification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.notification.id
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.notification.id_event
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    private Long idEvent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.notification.id_user
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    private Long idUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.notification.delivered_to_device
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    private Boolean deliveredToDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.notification.seen_in_web
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    private Boolean seenInWeb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.notification.id
     *
     * @return the value of webserver.notification.id
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.notification.id
     *
     * @param id the value for webserver.notification.id
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.notification.id_event
     *
     * @return the value of webserver.notification.id_event
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    public Long getIdEvent() {
        return idEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.notification.id_event
     *
     * @param idEvent the value for webserver.notification.id_event
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    public void setIdEvent(Long idEvent) {
        this.idEvent = idEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.notification.id_user
     *
     * @return the value of webserver.notification.id_user
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    public Long getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.notification.id_user
     *
     * @param idUser the value for webserver.notification.id_user
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.notification.delivered_to_device
     *
     * @return the value of webserver.notification.delivered_to_device
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    public Boolean getDeliveredToDevice() {
        return deliveredToDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.notification.delivered_to_device
     *
     * @param deliveredToDevice the value for webserver.notification.delivered_to_device
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    public void setDeliveredToDevice(Boolean deliveredToDevice) {
        this.deliveredToDevice = deliveredToDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.notification.seen_in_web
     *
     * @return the value of webserver.notification.seen_in_web
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    public Boolean getSeenInWeb() {
        return seenInWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.notification.seen_in_web
     *
     * @param seenInWeb the value for webserver.notification.seen_in_web
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    public void setSeenInWeb(Boolean seenInWeb) {
        this.seenInWeb = seenInWeb;
    }
}