package mybatis.model.basic;

import java.util.Date;

public class Reservation {


    private Boolean confirmed;

    private Boolean confirmPending;

    private Boolean invitationPending;

    private Boolean attended;

    public Boolean getConfirmed() {
        return confirmed;
    }

    public void setConfirmed(Boolean confirmed) {
        this.confirmed = confirmed;
    }

    public Boolean getConfirmPending() {
        return confirmPending;
    }

    public void setConfirmPending(Boolean confirmPending) {
        this.confirmPending = confirmPending;
    }

    public Boolean getInvitationPending() {
        return invitationPending;
    }

    public void setInvitationPending(Boolean invitationPending) {
        this.invitationPending = invitationPending;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.reservation.id
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.reservation.id_event
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    private Long idEvent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.reservation.id_user
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    private Long idUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.reservation.time
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.reservation.id
     *
     * @return the value of webserver.reservation.id
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.reservation.id
     *
     * @param id the value for webserver.reservation.id
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.reservation.id_event
     *
     * @return the value of webserver.reservation.id_event
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public Long getIdEvent() {
        return idEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.reservation.id_event
     *
     * @param idEvent the value for webserver.reservation.id_event
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public void setIdEvent(Long idEvent) {
        this.idEvent = idEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.reservation.id_user
     *
     * @return the value of webserver.reservation.id_user
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public Long getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.reservation.id_user
     *
     * @param idUser the value for webserver.reservation.id_user
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.reservation.time
     *
     * @return the value of webserver.reservation.time
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.reservation.time
     *
     * @param time the value for webserver.reservation.time
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }

    public Boolean getAttended() {
        return attended;
    }

    public void setAttended(Boolean attended) {
        this.attended = attended;
    }
}