package mybatis.model.basic;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.user_role.id
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.user_role.description
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.user_role.id
     *
     * @return the value of webserver.user_role.id
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.user_role.id
     *
     * @param id the value for webserver.user_role.id
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.user_role.description
     *
     * @return the value of webserver.user_role.description
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.user_role.description
     *
     * @param description the value for webserver.user_role.description
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}