package mybatis.model;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.address.id
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.address.address_line_1
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    private String addressLine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.address.address_line_2
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    private String addressLine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.address.city
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.address.postal_code
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    private Integer postalCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.address.id
     *
     * @return the value of webserver.address.id
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.address.id
     *
     * @param id the value for webserver.address.id
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.address.address_line_1
     *
     * @return the value of webserver.address.address_line_1
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.address.address_line_1
     *
     * @param addressLine1 the value for webserver.address.address_line_1
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1 == null ? null : addressLine1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.address.address_line_2
     *
     * @return the value of webserver.address.address_line_2
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.address.address_line_2
     *
     * @param addressLine2 the value for webserver.address.address_line_2
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2 == null ? null : addressLine2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.address.city
     *
     * @return the value of webserver.address.city
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.address.city
     *
     * @param city the value for webserver.address.city
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.address.postal_code
     *
     * @return the value of webserver.address.postal_code
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    public Integer getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.address.postal_code
     *
     * @param postalCode the value for webserver.address.postal_code
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    public void setPostalCode(Integer postalCode) {
        this.postalCode = postalCode;
    }
}