package mybatis.model;

import java.util.Date;
import java.util.List;

public class AppUser {

    private List<UserRole> listRoles;

    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.app_user.username
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.app_user.password1
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    private String password1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.app_user.enabled
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.app_user.email
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.app_user.birth_date
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    private Date birthDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.app_user.id
     *
     * @return the value of webserver.app_user.id
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.app_user.id
     *
     * @param id the value for webserver.app_user.id
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.app_user.username
     *
     * @return the value of webserver.app_user.username
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.app_user.username
     *
     * @param username the value for webserver.app_user.username
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.app_user.password1
     *
     * @return the value of webserver.app_user.password1
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public String getPassword1() {
        return password1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.app_user.password1
     *
     * @param password1 the value for webserver.app_user.password1
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public void setPassword1(String password1) {
        this.password1 = password1 == null ? null : password1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.app_user.enabled
     *
     * @return the value of webserver.app_user.enabled
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.app_user.enabled
     *
     * @param enabled the value for webserver.app_user.enabled
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.app_user.email
     *
     * @return the value of webserver.app_user.email
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.app_user.email
     *
     * @param email the value for webserver.app_user.email
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.app_user.birth_date
     *
     * @return the value of webserver.app_user.birth_date
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.app_user.birth_date
     *
     * @param birthDate the value for webserver.app_user.birth_date
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.app_user.id
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public List<UserRole> getListRoles() {
        return listRoles;
    }

    public void setListRoles(List<UserRole> listRoles) {
        this.listRoles = listRoles;
    }
}