package mybatis.model;

public class UserRoleMN {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.user_role_mn.id
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.user_role_mn.id_user
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    private Long idUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.user_role_mn.id_role
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    private Long idRole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.user_role_mn.id
     *
     * @return the value of webserver.user_role_mn.id
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.user_role_mn.id
     *
     * @param id the value for webserver.user_role_mn.id
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.user_role_mn.id_user
     *
     * @return the value of webserver.user_role_mn.id_user
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public Long getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.user_role_mn.id_user
     *
     * @param idUser the value for webserver.user_role_mn.id_user
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.user_role_mn.id_role
     *
     * @return the value of webserver.user_role_mn.id_role
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public Long getIdRole() {
        return idRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.user_role_mn.id_role
     *
     * @param idRole the value for webserver.user_role_mn.id_role
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    public void setIdRole(Long idRole) {
        this.idRole = idRole;
    }
}