package mybatis.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.user.id
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.user.first_name
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.user.last_name
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.user.phone_number
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    private Integer phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.user.email
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webserver.user.id_address
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    private Integer idAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.user.id
     *
     * @return the value of webserver.user.id
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.user.id
     *
     * @param id the value for webserver.user.id
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.user.first_name
     *
     * @return the value of webserver.user.first_name
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.user.first_name
     *
     * @param firstName the value for webserver.user.first_name
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.user.last_name
     *
     * @return the value of webserver.user.last_name
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.user.last_name
     *
     * @param lastName the value for webserver.user.last_name
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.user.phone_number
     *
     * @return the value of webserver.user.phone_number
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    public Integer getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.user.phone_number
     *
     * @param phoneNumber the value for webserver.user.phone_number
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    public void setPhoneNumber(Integer phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.user.email
     *
     * @return the value of webserver.user.email
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.user.email
     *
     * @param email the value for webserver.user.email
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webserver.user.id_address
     *
     * @return the value of webserver.user.id_address
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    public Integer getIdAddress() {
        return idAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webserver.user.id_address
     *
     * @param idAddress the value for webserver.user.id_address
     *
     * @mbggenerated Sun Nov 02 14:16:39 CET 2014
     */
    public void setIdAddress(Integer idAddress) {
        this.idAddress = idAddress;
    }
}