package mybatis.dao;

import mybatis.model.basic.Address;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.address
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.address
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.address
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int insertSelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.address
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    Address selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.address
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int updateByPrimaryKeySelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.address
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int updateByPrimaryKey(Address record);
}