package mybatis.dao;

import mybatis.model.complex.AppUser;
import mybatis.model.basic.UserRole;
import mybatis.model.complex.FullProfile;
import mybatis.model.complex.UserEventFilter;

import java.util.List;

public interface AppUserMapper {

    //custom
    //vyzaduje includy
    List<UserRole> selectRolesList(Long id);

    List<AppUser> selectUsersWithRole(Long idRole);

    //custom
    AppUser selectByUsername(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.app_user
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.app_user
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int insert(AppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.app_user
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int insertSelective(AppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.app_user
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    AppUser selectByPrimaryKey(Long id);

    FullProfile selectFullProfileByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.app_user
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int updateByPrimaryKeySelective(AppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.app_user
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int updateByPrimaryKey(AppUser record);

    int updateByPrimaryKeyWithBLOBs(AppUser record);

    AppUser selectProfileByPrimaryKey(Long id);

    UserEventFilter selectByUsernameWithEventFilter(String name);

    List<AppUser> selectUsersWithRegionByRegionID(Long idRegion);
}