package mybatis.dao;

import mybatis.model.AppUser;
import mybatis.model.UserRole;

import java.util.List;

public interface AppUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.app_user
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.app_user
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    int insert(AppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.app_user
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    int insertSelective(AppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.app_user
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    AppUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.app_user
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    int updateByPrimaryKeySelective(AppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.app_user
     *
     * @mbggenerated Fri Dec 12 21:32:13 CET 2014
     */
    int updateByPrimaryKey(AppUser record);



    List<UserRole> selectRolesList(Long id);


}