package mybatis.dao;

import mybatis.model.basic.Country;

import java.util.List;

public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.country
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.country
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int insert(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.country
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int insertSelective(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.country
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    Country selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.country
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int updateByPrimaryKeySelective(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.country
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int updateByPrimaryKey(Country record);

    List<Country> selectAll();
}