package mybatis.dao;

import mybatis.handler.TwoDateTwoIntOneLong;
import mybatis.handler.TwoDateTwoIntParams;
import mybatis.model.complex.Event;

import java.util.List;

public interface EventMapper {


    //custom
    //vyzaduje includy


    List<Event> selectAllPublicAddressList();

    List<Event> selectAllOwnersEventsList(Long idOwner);

    Event selectPublicEventByPrimaryKey(Long idEvent);

    Event selectPrivateEventByPrimaryKey(Long idEvent);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int insert(mybatis.model.basic.Event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int insertSelective(mybatis.model.basic.Event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    Event selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int updateByPrimaryKeySelective(mybatis.model.basic.Event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int updateByPrimaryKey(mybatis.model.basic.Event record);

    List<Event> selectPublicEventPageBetweenDates(TwoDateTwoIntParams twoDateTwoIntParams);

    List<Event> selectPublicEventTypesPageBetweenDates(TwoDateTwoIntOneLong params);

    List<Event> selectPublicEventPageBetweenDatesAndUserFilter(TwoDateTwoIntOneLong params);

    List<Event> selectPublicEventPageThatHaventStarted(TwoDateTwoIntParams params);

    Long selectNumberOfEventsThatHaventStarted();
}