package mybatis.dao;

import mybatis.model.basic.EventFilter;
import mybatis.model.basic.EventType;

import java.util.List;

public interface EventFilterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_filter
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_filter
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int insert(EventFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_filter
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int insertSelective(EventFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_filter
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    EventFilter selectByPrimaryKey(Long id);

    List<EventType> selectEventFilterByUserId(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_filter
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int updateByPrimaryKeySelective(EventFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_filter
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int updateByPrimaryKey(EventFilter record);

}