package mybatis.dao;

import mybatis.model.basic.EventTypeMN;

public interface EventTypeMNMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_type_mn
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_type_mn
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int insert(EventTypeMN record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_type_mn
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int insertSelective(EventTypeMN record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_type_mn
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    EventTypeMN selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_type_mn
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int updateByPrimaryKeySelective(EventTypeMN record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_type_mn
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int updateByPrimaryKey(EventTypeMN record);
}