package mybatis.dao;

import mybatis.model.basic.EventType;

import java.util.List;

public interface EventTypeMapper {


    List<EventType> selectAllTypes();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_type
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_type
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int insert(EventType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_type
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int insertSelective(EventType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_type
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    EventType selectByPrimaryKey(Long id);

    List<EventType> selectEventTypesForEvent(Long idEvent);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_type
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int updateByPrimaryKeySelective(EventType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.event_type
     *
     * @mbggenerated Thu Mar 12 17:21:26 CET 2015
     */
    int updateByPrimaryKey(EventType record);
}