package mybatis.dao;

import mybatis.model.basic.Notification;

public interface NotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.notification
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.notification
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    int insert(Notification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.notification
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    int insertSelective(Notification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.notification
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    Notification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.notification
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    int updateByPrimaryKeySelective(Notification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.notification
     *
     * @mbggenerated Fri Mar 27 14:57:19 CET 2015
     */
    int updateByPrimaryKey(Notification record);
}