package mybatis.dao;

import mybatis.model.complex.Region;

import java.util.List;

public interface RegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.region
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.region
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int insert(Region record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.region
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int insertSelective(Region record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.region
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    Region selectByPrimaryKey(Long id);

    List<Region> selectAllRegions();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.region
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int updateByPrimaryKeySelective(Region record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.region
     *
     * @mbggenerated Wed Mar 11 15:22:30 CET 2015
     */
    int updateByPrimaryKey(Region record);

    Region selectByArea1(String area1);

    List<Region> selectCountryRegionsByCountryId(Long countryId);

    List<Region> selectFilteredRegionsByUsername(String username);

    List<Region> selectFilteredRegionsByUserId(Long userId);
}