package mybatis.dao;

import mybatis.handler.TwoLongParameters;
import mybatis.model.basic.Reservation;
import mybatis.model.complex.ReservationWithUser;

import java.util.List;

public interface ReservationMapper {


    List<Reservation> selectPendingInvitationsByUserID(Long idUser);

    List<Reservation> selectReservationsUserConfirmedByUserID(Long idUser);

    List<Reservation> selectReservationsForEventByEventId(Long eventId);

    List<ReservationWithUser> selectReservationsWithUserForEventByEventId(Long eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.reservation
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.reservation
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int insert(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.reservation
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int insertSelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.reservation
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    Reservation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.reservation
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int updateByPrimaryKeySelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.reservation
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int updateByPrimaryKey(Reservation record);

    int deleteByUserAndEventIDs(TwoLongParameters twoLongParameters);

    int updateByForeignKeysSelective(Reservation reservation);
}