package mybatis.dao;

import mybatis.model.SampleObject;


public interface SampleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table eod_report
     * 
     * @mbggenerated Wed Jul 03 00:39:54 CEST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table eod_report
     * 
     * @mbggenerated Wed Jul 03 00:39:54 CEST 2013
     */
    int insert(SampleObject record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table eod_report
     * 
     * @mbggenerated Wed Jul 03 00:39:54 CEST 2013
     */
    int insertSelective(SampleObject record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table eod_report
     * 
     * @mbggenerated Wed Jul 03 00:39:54 CEST 2013
     */
    SampleObject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table eod_report
     * 
     * @mbggenerated Wed Jul 03 00:39:54 CEST 2013
     */
    int updateByPrimaryKeySelective(SampleObject record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table eod_report
     * 
     * @mbggenerated Wed Jul 03 00:39:54 CEST 2013
     */
    int updateByPrimaryKey(SampleObject record);



}