package mybatis.dao;

import mybatis.model.basic.UserRoleMN;

public interface UserRoleMNMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.user_role_mn
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.user_role_mn
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int insert(UserRoleMN record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.user_role_mn
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int insertSelective(UserRoleMN record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.user_role_mn
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    UserRoleMN selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.user_role_mn
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int updateByPrimaryKeySelective(UserRoleMN record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.user_role_mn
     *
     * @mbggenerated Mon Dec 22 14:05:31 CET 2014
     */
    int updateByPrimaryKey(UserRoleMN record);
}