package mybatis.dao;

import mybatis.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.user
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.user
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.user
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.user
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.user
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webserver.user
     *
     * @mbggenerated Sun Nov 02 15:01:31 CET 2014
     */
    int updateByPrimaryKey(User record);
}